plugins {
    id 'java'
    id 'org.openrewrite.rewrite'
}

repositories {
    mavenLocal()
    mavenCentral()
}

rewrite {
    activeRecipe('com.gmail.unmacaque.Rewrite')

    configFile("${project.rootDir}/rewrite.yml")
}

dependencies {
    rewrite libs.openrewrite.spring
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs << "-Werror"
}

test {
    useJUnitPlatform()
}
