server:
  port: 8888
spring:
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/cloud/{application}
  config:
    name: configserver
  profiles:
    active: native
