[versions]
dependencyManagement = "1.1.7"
springBoot = "3.4.1"
springCloudContract = "4.2.0"

[libraries]
dependencyManagement = { module = "io.spring.gradle:dependency-management-plugin", version.ref = "dependencyManagement" }

springBoot = { module = "org.springframework.boot:spring-boot-gradle-plugin", version.ref = "springBoot" }

springCloudContract = { module = "org.springframework.cloud:spring-cloud-contract-gradle-plugin", version.ref = "springCloudContract" }
