[versions]
dependencyManagement = "1.1.7"
springBoot = "4.1.0"

[libraries]
dependencyManagement = { module = "io.spring.gradle:dependency-management-plugin", version.ref = "dependencyManagement" }

springBoot = { module = "org.springframework.boot:spring-boot-gradle-plugin", version.ref = "springBoot" }
